[Draft] Disable ledger accounts for Ethereum chains
chainapsis/keplr-wallet pull request #314
Opened 2022-03-07 08:35 UTC by austinchandra

Since Ledgers on Keplr are hard-coded to use the `coinType = 118`, we must disable them on Evmos to prevent users from using invalid address and getting funds stuck.

![ledger-demo](https://user-images.githubusercontent.com/11379797/156996073-cf6cba7f-fe0f-494d-8805-05705eda76ea.gif)

2022-03-07 08:41 UTC, fedekunze commented on packages/extension/src/pages/main/account.tsx
> +            ? "Key Rejected"
```suggestion
            ? "Unsupported Key"
```

2022-03-07 08:41 UTC, fedekunze commented on packages/background/src/keyring/keyring.ts
> +      if (coinType === 60) {
```suggestion
      if (coinType != 118) {
```

2022-03-07 10:00 UTC, fedekunze commented
I'd be nice to add an error message too

2022-03-07 10:01 UTC, fedekunze commented
@austinchandra can we disable the buttons too?

2022-03-08 07:46 UTC, birkasecorba commented
+1 on hiding the buttons and [this](https://github.com/chainapsis/keplr-wallet/pull/314#discussion_r820482373)

2022-03-09 05:10 UTC, austinchandra commented
Pushed a fix with the above, let me know your thoughts

![Screen Shot 2022-03-08 at 9 10 30 PM](https://user-images.githubusercontent.com/11379797/157377069-99822a65-4cdf-459a-84a7-ae0323bb0255.png)

2022-03-09 06:42 UTC, austinchandra commented
Another option:

![Screen Shot 2022-03-08 at 10 41 40 PM](https://user-images.githubusercontent.com/11379797/157386609-91350905-3c93-4417-91f0-26ed62c9a7c4.png)

2022-03-09 18:39 UTC, austinchandra commented
Updated to use icon:

![Screen Shot 2022-03-09 at 10 38 37 AM](https://user-images.githubusercontent.com/11379797/157508965-b1cd2fbc-8b7e-4870-865e-ddd224e377d9.png)
![Screen Shot 2022-03-09 at 10 38 43 AM](https://user-images.githubusercontent.com/11379797/157508963-74d21f52-452a-4889-9d55-fd7f1865eb01.png)

2022-03-14 17:13 UTC, zmanian commented
LFG

2022-03-14 17:13 UTC, zmanian approved these changes

2022-03-15 16:05 UTC, Thunnini reviewed
(deleted)

2022-03-15 16:07 UTC, Thunnini requested changes

2022-03-15 16:07 UTC, Thunnini commented on packages/stores/src/account/base.ts
> +      this._walletStatus = WalletStatus.Rejected;
`WalletStatus.Rejected` status is designed to represent the status of rejection when a user rejects a permission from external websites(user's directly denying permissions when prompted, or in the case of user turning off the extension w/o entering password).

That being said, this should not be used to emit an error for general cases.

2022-03-15 16:07 UTC, Thunnini commented on packages/extension/src/pages/main/account.tsx
> +      {accountInfo.walletStatus === WalletStatus.Rejected && (
Just because a wallet status is rejected does not guarantee that the error comes from loading pub keys

2022-03-15 17:03 UTC, Thunnini commented
proposed solution: make `rejectedReason: Error | undefined` field to account store, and if its a rejected state, handle the ui according to the error message.

I will think of a better method to solve this, as of now I would go ahead merge this PR when modified as above

2022-03-20 00:59 UTC, austinchandra commented
Updated with the proposed changes

2022-03-22 20:42 UTC, merged