Add analytics setting option
chainapsis/keplr-wallet pull request #753
Opened 2023-06-09 14:50 UTC by HeesungB

Added an analytics setting under Privacy in Settings.

2023-06-12 03:21 UTC, Thunnini commented
이거 사실 background의 analytics service에서도 처리해줘야 합니다.
analytics service에서 disabled field 만드시고 mobx observable + autorun으로 init에서 자동으로 storage에 sync 되도록 해주시고
disabled 상태에서는 logEvent에서 아무것도 안하도록 하시면 돼요.
그리고 프론트에서 disabled 값 설정할 수 있는 message를 따로 만드시고
만드신 UI의 toggle 옵션에서 값에 따라서 message 보내서 background의 analytics service enable/disable 적절히 시켜주세요

2023-06-12 03:22 UTC, Thunnini requested changes
이거 사실 background의 analytics service에서도 처리해줘야 합니다.
analytics service에서 disabled field 만드시고 mobx observable + autorun으로 init에서 자동으로 storage에 sync 되도록 해주시고
disabled 상태에서는 logEvent에서 아무것도 안하도록 하시면 돼요.
그리고 프론트에서 disabled 값 설정할 수 있는 message를 따로 만드시고
만드신 UI의 toggle 옵션에서 값에 따라서 message 보내서 background의 analytics service enable/disable 적절히 시켜주세요

2023-06-13 06:04 UTC, Thunnini requested changes

2023-06-13 06:04 UTC, Thunnini commented on packages/background/src/analytics/messages.ts
> +  override approveExternal(): boolean {
이거 true 반환하면 외부 웹페이지에서도 이 message 보낼 수 있어요 주의해야해요
지워주세요

2023-06-13 07:19 UTC, Thunnini commented on packages/extension/src/pages/setting/security/index.tsx
> +                        new SetDisableAnalyticsMsg(usingAnalytics)
"using-analytics"가 "true"면 `usingAnalytics`가 true가 되서 이렇게 메세지 보내면 백그라운드에서 analytics service가 disabled되는거 아닌가요? 반대로 된 것 같은뎁

2023-06-13 07:26 UTC, HeesungB commented on packages/extension/src/pages/setting/security/index.tsx
> +                        new SetDisableAnalyticsMsg(usingAnalytics)
```
const usingAnalytics = localStorage.getItem("using-analytics") !== "false";
```

변수 이름을 잘못 정한 것 같아요. 변수명을 수정할께요!

2023-06-13 10:05 UTC, Thunnini requested changes

2023-06-13 10:05 UTC, Thunnini commented on packages/extension/src/pages/setting/security/index.tsx
> +                        new SetDisableAnalyticsMsg(!disableAnalytics)
`new SetDisableAnalyticsMsg(!disableAnalytics)`가 `new SetDisableAnalyticsMsg(disableAnalytics)`가 되어야하는거 아닌가요...? 🤔

2023-06-13 10:10 UTC, Thunnini commented on packages/extension/src/pages/setting/security/index.tsx
> +                        new SetDisableAnalyticsMsg(!disableAnalytics)
아 이해했다

2023-06-13 10:11 UTC, merged