Support EVM compatible features
chainapsis/keplr-wallet pull request #902
Opened 2023-11-17 13:11 UTC by delivan

2023-11-17 13:14 UTC, delivan commented on packages/extension/src/config.ts
> +      },
for test

2023-11-17 13:14 UTC, delivan commented on packages/extension/src/stores/chain/index.tsx
> +      // this.updateChainInfosFromBackground(),
for test

2024-01-15 03:45 UTC, randy75828 commented
Hi! when will this possibly be merged? Need this PR in as it is blocking our keplr evm signing now 
https://github.com/chainapsis/keplr-wallet/issues/800

2024-01-26 09:10 UTC, junw3i commented
@Thunnini when can this merged? evm signMessage does not work when the evm chain id differs from the cosmos's chain id

2024-01-29 13:08 UTC, Thunnini commented on packages/background/src/keyring-ethereum/messages.ts
> +      isEthereumHexAddress(this.signer);
@ethersproject/address의 isAddress()를 보면 0x가 있거나 없거나 허용하고 ICAP(?)라고 하는 format도 허용하는 것처럼 보입니다. 그렇기 때문에 isAddress()를 쓰는것보다 더 확실히 예측할 수 있게 더 엄밀한 validation으로 바꿔야한다고 생각합니다 (ex. 0x를 포함되면 안되고 hex 40글자여야함 등...)

2024-01-29 13:09 UTC, Thunnini commented on packages/background/src/keyring-ethereum/service.ts
> +    ).toHex(true);
이 경우 address가 그 머시더라 쨋든 eip에서 case sensitive로 checksum하는 그거를 주소가 따르지 않으면 Signer mismatched 오류가 뜨게될것으로 보이는데 사실 그 checksum은 기본적으로는 UI에서 잘 처리하면 되는거라 background에서 그 checksum을 고려할지 무시할지를 생각해봐야합니다. 그리고 checksum을 고려한다고 해도 오류 메세지가 "Signer mismatched" 이걸로 뜨면 안될듯

2024-01-29 13:12 UTC, Thunnini commented on packages/background/src/keyring-ethereum/service.ts
> +  static isEvmLike(chainInfo: ChainInfo): boolean {
여러 코드에서 머시기.evm!를 쓰게되는 것 같은데 이렇게 하는 것보다 그냥 이 static method에서 (evm object)/undefined를 반환하게 해서 undefined가 아닐땐 그냥 반환된 evm object를 쓰는 것은 어떨까요

2024-01-29 13:14 UTC, Thunnini commented on packages/background/src/tx-ethereum/service.ts
> +      const intervalId = setInterval(
const intervalId로 선언은 여기서 되어있는데 clearInterval(intervalId)는 위쪽에서 하게 되는데... 이게 원래 js라서 되는건가... 근데 js라고 해도 좀 어색해보이기 때문에 쉽게 수정할 수 있다면 약간 수정해야하지 않을까 싶습니다...

2024-01-29 13:18 UTC, Thunnini commented on packages/common/src/denom/index.ts
> +    if (split.length < 1 || split.length > 3) {
/(\w+):(\w+):(.+)/로 인해서 각각의 : 사이의 단어(?)는 무조건 한글자를 넘어야 하는데 로직이 바뀌면서 "    " 이런 경우는 오류를 던지지 않게 되었기 때문에 대충 split마다 trim()을 한다던가 하는 조치가 있어야할 것 같습니다

2024-01-29 13:21 UTC, Thunnini commented on packages/provider/src/core.ts
> +  async sendEthereumTx(chainId: string, rawTx: string): Promise<string> {
rawTx 인자는 hex string으로 넣는건가요? Uint8Array로 해도 될 것 같긴 한데... 그냥 string으로 해놓으면 이름만보고는 hex인지 base64인지 알수가 없어서...

2024-01-31 06:25 UTC, delivan commented on packages/background/src/keyring-ethereum/messages.ts
> +      isEthereumHexAddress(this.signer);
네넵 그래야겠네요. 예시 들어준거에 '0x' 포함하면 안되는 이유는 뭐에요? '0x 빼고 hex 40글자여야 한다' 인건가요? @Thunnini

2024-01-31 06:26 UTC, delivan commented on packages/background/src/keyring-ethereum/service.ts
> +    ).toHex(true);
네넵 checksum 고려해서 검증하도록 수정하겠습니다!

2024-01-31 06:46 UTC, delivan commented on packages/background/src/keyring-ethereum/service.ts
> +  static isEvmLike(chainInfo: ChainInfo): boolean {
아 이해했습니다. 좋은 것 같습니다!

2024-01-31 06:48 UTC, delivan commented on packages/background/src/tx-ethereum/service.ts
> +      const intervalId = setInterval(
js라 되는거긴 한데, 어색해보이긴하네요. 수정해놓겠습니다!

2024-01-31 06:49 UTC, delivan commented on packages/common/src/denom/index.ts
> +    if (split.length < 1 || split.length > 3) {
네넵 수정해놓겠습니다!

2024-01-31 06:56 UTC, delivan commented on packages/provider/src/core.ts
> +  async sendEthereumTx(chainId: string, rawTx: string): Promise<string> {
hex긴 한데 타입만봐서는 모르겠네요. `sendTx`와 마찬가지로 Uint8Array로 통일하겠습니다!

2024-02-20 12:14 UTC, Thunnini commented on packages/stores-eth/src/account/base.ts
> +        : {
아마 이 부분이 native eth(?)를 보내는 경우의 json rpc인 것 같은데 보낼 수량(amount)에 대한게 request에 있어야할 것 같은데 없네욤?

2024-02-20 12:23 UTC, Thunnini commented on packages/background/src/tx-ethereum/service.ts
> +          if (txReceipt.status === EthTxStatus.Success) {
지금 cosmos account의 기준으로 보면 tx events에서 `onBroadcastFailed`는 rpc로 tx를 보내는 request 자체가 실패했을때 `onBroadcasted`는 rpc로 tx를 보내는 request까지 성공했을때 `onFulfill`은 tx가 블록에 담겨서 commit되었을 때인데 여기서 `onFulfill`은 tx가 성공했는지 실패했는지랑 상관없이 event를 실행시켜줘요
근데 ethereum account의 경우는 실패했을때는 `onFulfill`을 실행시키지 않고 `onBroadcastFailed`를 실행시키는 것 같은데 이런 차이점을 안두는게 나을 것 같아요

2024-02-20 12:33 UTC, Thunnini requested changes

2024-02-20 12:33 UTC, Thunnini commented on packages/stores/src/query/balances.ts
> -        let balanceImpl: IObservableQueryBalanceImpl | undefined;
원래는 balanceImpl를 얻을 수 없으면 오류를 던졌는데 여기서는 balanceImpl가 없으면 그냥 넘어가게 바뀐 것 같은데 얘는 좀 코어한 부분이라 이런 변환를 꼭 해야하는 이유가 있는게 아니면 안해야할 것 같아요

2024-02-20 12:41 UTC, Thunnini commented on packages/stores-eth/src/erc20-currency-registrar.ts
> +export class EVMChainERC20CurrencyRegistrar {
아마 얘는 필요없을거에요 지워주세요

2024-02-20 12:55 UTC, delivan commented on packages/stores-eth/src/account/base.ts
> +    const tempRecipient = isEthereumHexAddress(recipient) ? recipient : sender;
native evm 토큰 send시 send 화면에서 simulate된 fee를 보여줘야 되는데, send 화면 마운트됐을 때 당연히 recipient 주소가 없어서, simulate 성공하게하려고 이렇게 처리했어요. 다른 방법 또 있을까요?

2024-02-20 12:57 UTC, delivan commented on packages/stores-eth/src/account/base.ts
> +      gasUsed: Number(estimateGasResponse.data.result),
일단 native 토큰 / erc20 send 수준에선 대략 20000 ~ 70000 정도에요.

2024-02-20 12:58 UTC, delivan commented on packages/background/src/token-erc20/service.ts
> +  protected readonly legacyKVStore: KVStore;
넵 삭제하겠습니당

2024-02-20 13:05 UTC, delivan commented on packages/background/src/tx-ethereum/service.ts
> +          params: [Buffer.from(tx).toString()],
헐 지금까지 잘 동작하긴했는데 명시하는게 좋겠네요;;

2024-02-20 13:06 UTC, delivan commented on packages/chain-validator/src/schema.ts
> +    contractAddress: Joi.string().required(),
오 그게 더 좋을 것 같아욤

2024-02-20 13:10 UTC, delivan commented on packages/stores-eth/src/account/base.ts
> +        : {
아 이거 원래 amount 보내다가 무슨 이유가 있어서 바꿨는데.. 이유 다시 생각해볼게요.
일단 0으로도 estimate 잘 되고 gasUsed에 영향이 없어서 바꿔놓긴 했어요.

2024-02-22 04:42 UTC, delivan commented on packages/stores/src/query/balances.ts
> -        let balanceImpl: IObservableQueryBalanceImpl | undefined;
이전 로직으로 다시 변경하고, `ObservableQueryCosmosBalanceRegistry.getBalanceImpl` 에서 파라미터 bech32Address 가 bech32 아니면 undefined 리턴하도록 했습니다.

2024-02-22 13:04 UTC, delivan commented on packages/stores-eth/src/account/base.ts
> +        : {
이거 이유가 `BigNumber.toHexString()`이 zero padding 붙인 hex string을 리턴하는데, json rpc 클라이언트에서 zero padding 있으면 에러를 응답해서 바꿨었어요.

ethersjs 의 `hexValue` 라는 함수로 zero padding 제거한 hex string 값을 사용하도록 변경했어요.

2024-03-13 08:22 UTC, merged